// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using ScholarLog.Data;
using ScholarLog.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MonDbContext), typeof(MonDbContextModel))]
