<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>

        <!-- Optimisation de la compilation -->
        <InvariantGlobalization>true</InvariantGlobalization>
	    
        <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
        <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
        <EnableUnsafeAssemblyLoadSupport>false</EnableUnsafeAssemblyLoadSupport>


        <!-- Pas de debug pour l'utilisateur final -->
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
        <StackTraceSupport>false</StackTraceSupport>
        <DebuggerSupport>false</DebuggerSupport>
        <EventSourceSupport>false</EventSourceSupport>
        <MetricsSupport>false</MetricsSupport>
        <MetadataUpdaterSupport>false</MetadataUpdaterSupport>

        <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport> <!-- Pas de requette web -->
        <ServerGarbageCollection>false</ServerGarbageCollection> <!-- pas un serveur-->

        <!-- Voir pour désactiver TRIM en cas de problèmes -->
        <PublishTrimmed>true</PublishTrimmed> 
        <TrimMode>partial</TrimMode> <!-- sûr : partial. Incertain : full-->
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>


        <ApplicationIcon>Assets\Images\ScholarLogLogoEx.ico</ApplicationIcon>
        <Version>0.0.1</Version>
        <Title>ScholarLog</Title>
        <Authors>Lukas Hofer</Authors>
        <Description>Interface de gestions de résultats scolaire</Description>
        <PackageProjectUrl>https://github.com/Hoferlukaslh/ScholarLog</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Hoferlukaslh/ScholarLog</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <!--  déclaration des ressources -->

        <!-- Polices d'écriture -->
        <AvaloniaResource Include="Assets\Fonts\Helvetica\Helvetica.ttf" /> <!-- Textes -->
        <AvaloniaResource Include="Assets\Fonts\Phosphor\Phosphor.ttf" />   <!-- Pictogrammes -->

        <!-- Logos -->
        <AvaloniaResource Include="Assets\Images\ScholarLogLogoTSombre.ico" />
        <AvaloniaResource Include="Assets\Images\ScholarLogLogoTClair.ico" />
        <AvaloniaResource Include="Assets\Images\ScholarLogLogoEx.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />

        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" Condition="'$(Configuration)' == 'Debug'" />

        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="PDFtoImage" Version="4.0.0" /> <!-- Conflit avec SkiaSharp, V5 fonctionne pas sur linux -->
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Views\Pages\HomePage.axaml" />
      <AdditionalFiles Include="Views\Pages\JournalPage.axaml" />
      <AdditionalFiles Include="Views\Pages\NotesPage.axaml" />
      <AdditionalFiles Include="Views\Pages\SettingsPage.axaml" />
    </ItemGroup>
</Project>
